{% set name = "SpectroChemPy" %}
{% set version = environ.get('GIT_DESCRIBE_TAG', '0.1')|string|replace('-','_') %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ../../

build:
  number:
    - {{ environ.get('GIT_DESCRIBE_NUMBER', '0') }}
  entry_points:
    - scpy=spectrochempy.scripts.launch_api:main
  script:  "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
  build:
    - python                    {{ python }}.*
    - setuptools
    - setuptools_scm
    - nodejs
    - jupyterlab
  run:
    - numpy                     {{ numpy }}.*
    - scipy
    - matplotlib
    - traitlets
    - pint                      {{ pint }}.*
    - cantera
    - quadprog
    - brukeropusreader
    - xlrd
    - numba
    - pandas
    - tqdm
    - colorama
    - setuptools_scm
    - git
    - ipython
    - jupyterlab
    - ipympl
    - nodejs
    - ipykernel
    - ipywidgets
    - widgetsnbextension
    - quaternion

test:
  imports:
    - spectrochempy
  commands:
    - scpy

about:
  home: "https://redmine.spectrochempy.fr"
  license: CeCILL-B
  license_family: OTHER
  summary: "Processing, analysis and modelling Spectroscopic data for Chemistry with Python"
  doc_url: "https://www.spectrochempy.fr"
  dev_url: "https://bitbucket.org/spectrocat/spectrochempy"

extra:
  recipe-maintainers:
    - fernandezc
