{% set name = "SpectroChemPy" %}
{% set version = "0.1.17" %}
{% set number = 0 %}

# see this  for a description of the sections
# https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: ../../
  git_rev: "{{ version }}"

build:
  number: 0
  noarch: python
  entry_points:
    - scpy=spectrochempy.scripts.launch_api:main

  # If the installation is complex, or different between Unix and Windows,
  # use separate bld.bat and build.sh files instead of this key. By default,
  # the package will be built for the Python versions supported by conda-forge
  # and for all major OSs. Add the line "skip: True  # [py<35]" (for example)
  # to limit to Python 3.5 and newer, or "skip: True  # [not win]" to limit
  # to Windows.

  script:
    - {{ PYTHON }} -m pip install . -vv
    - jupyter labextension install @jupyter-widgets/jupyterlab-manager jupyter-matplotlib

requirements:
  host:
    - pip
    - python
  build:
    - python           {{ python }}.*
    - setuptools
    - setuptools_scm
    - nodejs
    - jupyterlab
  run:
    - python
    - numpy
    - matplotlib
    - traitlets
    - pint             {{ pint }}.*
    - quaternion
    - scipy
    - colorama
    - setuptools_scm
    - ipython
    - jupyterlab
    - ipympl
    - nodejs
    - ipykernel
    - ipywidgets
    - widgetsnbextension
    - xlrd
    - numba
    - pandas
    - cantera
    - quadprog
    - pyqt
    - tqdm
    
test:
  imports:
    - spectrochempy

  commands:
    - scpy --help
    - pytest

  # test-only requirements
  requires:
      - pytest
      - scikit-image

  # needed test files
  source_files:
      - tests/

about:
  home: "https://redmine.spectrochempy.fr"
  license: CeCILL-B
  license_family: OTHER
  summary: "Processing, analysis and modelling Spectroscopic data for Chemistry with Python"
  doc_url: "https://www.spectrochempy.fr"
  dev_url: "https://bitbucket.org/spectrocat/spectrochempy"

extra:
  recipe-maintainers:
    - fernandezc
