{% set name = "SpectroChemPy" %}
{% set version = environ['VERSION'] %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ../

build:
  script_env:
    - VERSION
    - CONDA_BLD_PATH
  string: {{ environ['DEVSTRING'] }}
  noarch: python
  entry_points:
    - scpy=spectrochempy.scripts.launch_api:main
  script:  "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
  build:
    - python
    - setuptools
    - setuptools_scm
    - nodejs
    - jupyterlab
  run:
    - numpy
    - scipy
    - matplotlib
    - traitlets
    - pint=0.9
    - cantera
    - quadprog
    - brukeropusreader
    - xlrd
    - numba
    - pandas
    - tqdm
    - colorama
    - setuptools_scm
    - git
    - ipython
    - jupyterlab
    - ipympl
    - nodejs
    - ipykernel
    - ipywidgets
    - widgetsnbextension
    - quaternion
  test:
    - python                {{ python }}

test:
  imports:
    - spectrochempy

about:
  home: "https://redmine.spectrochempy.fr"
  license: CeCILL-B
  license_family: OTHER
  summary: "Processing, analysis and modelling Spectroscopic data for Chemistry with Python"
  doc_url: "https://www.spectrochempy.fr"
  dev_url: "https://github.com/spectrochempy/spectrochempy"

extra:
  recipe-maintainers:
    - fernandezc
