version: "2"
plugins:
  pep8:
    enabled: true
checks:
  file-lines:
    config:
      threshold: 6000
  argument-count:
    config:
      threshold: 15
  complex-logic:
    config:
      threshold: 500
  method-lines:
    config:
      threshold: 300
  method-count:
    config:
      threshold: 50
  method-complexity:
    config:
      threshold: 50
  similar-code:
    config:
      threshold: 50
exclude_patterns:
  - ".ci/"
  - ".git/"
  - ".eggs/"
  - ".github/"
  - "conda/"
  - "docker/"
  - "docs/"
  - "env"
  - "scp_data"
  - "*.egg_info/"
  - "tests/"