version: "2"
plugins:
  pep8:
    enabled: false
checks:
  file-lines:
    config:
      threshold: 6000
  argument-count:
    config:
      threshold: 15
  complex-logic:
    config:
      threshold: 500
  method-lines:
    config:
      threshold: 300
  method-count:
    config:
      threshold: 100
  method-complexity:
    config:
      threshold: 150
  similar-code:
    config:
      threshold: 100
  nested-control-flow:
    config:
      threshold: 10
  return-statements:
    config:
      threshold: 20

exclude_patterns:
  - ".ci/"
  - ".git/"
  - ".eggs/"
  - ".github/"
  - ".conda/"
  - "docker/"
  - "docs/"
  - "env"
  - "scp_data"
  - "*.egg-info/"
  - "tests/"
  - "build/"
  - "scripts/"
