version: "2"
plugins:
  pep8:
    enabled: true
checks:
  file-lines:
    config:
      threshold: 6000
  argument-count:
    config:
      threshold: 10
  complex-logic:
    config:
      threshold: 500
  method-lines:
    config:
      threshold: 300
  method-count:
    config:
      threshold: 50
  method-complexity:
    config:
      threshold: 30
  similar-code:
    config:
      threshold: 50
exclude_patterns:
  - ".git/"
  - "tests/"
  - "**/extern/"
  - "docs/"