queries:
  - exclude:
      - py/import-and-import-from
      - py/call-to-non-callable
extraction:
  python:
    python_setup:
      version: 3
    index:
      exclude:
        - ".ci/"
        - ".git/"
        - ".eggs/"
        - ".github/"
        - "conda/"
        - "docker/"
        - "docs/"
        - "env"
        - "scp_data"
        - "*.egg_info/"
        - "tests/"
