queries:
  - exclude: py/import-and-import-from
extraction:
  python:
    python_setup:
      version: 3
    index:
      exclude:
        - ".git/"
        - "tests/"
        - "**/extern"
        - "docs/"
