#!/bin/sh

#source ~/.bash_profile
#conda activate scpy-dev

# to make it work with matplotlib/latex
#export PATH=$PATH:/Library/TeX/texbin/

# test everything and do not commit if errors
# pytest -x "not example" tests --nodisplay --reset_config  || exit 1

## install to check setup
#pip uninstall -y spectrochempy
#pip install -e . || exit 1

#python docs/builddocs.py html


