#!/bin/bash

# to use the pre-commit in the source git_hooks directory
# in the Spectrochempy/.git/hooks  directory
# ln -s ../../git_hooks/pre-commit pre-commit
# or run pip install -e . to install it automatically

# run test for python 3.6
#-------------------------


# to make it work with SourceTree (assuming anaconda is used)
source ~/.bash_profile

# to make it work with matplotlib/latex
export PATH=$PATH:/Library/TeX/texbin/

# test everything
py.test -x tests || exit 1

# install to check setup
pip uninstall -y spectrochempy
pip install -e . || exit 1

# make docs
python scripts/make_scp_docs.py clean html release

# add files modified
git add -A

# test also python27
#--------------------

# to make it work with SourceTree (assuming anaconda is used)
# source activate scp27

# run test
# py.test -x tests || exit 1


