#!/bin/bash

# run test for python 3.6
#-------------------------

# to make it work with SourceTree (assuming anaconda is used)
# probably need to change this to account for windows developper..
# TODO: activate in windows?

source ~/.bash_profile

# to make it work with matplotlib/latex
export PATH=$PATH:/Library/TeX/texbin/

# test everything and do not commit if errors
py.test -x tests || exit 1

## add last file
#git add -A
#
## getb last commit message
#OUTPUT="$(git log -1 --pretty=%B)"
#git commit --no-verify --amend -m "${OUTPUT}"
#
#python docs/builddocs.py clean
#python docs/builddocs.py html || exit 1
#
## add last file
#git add -A
#
## getb last commit message
#OUTPUT="$(git log -1 --pretty=%B)"
#git commit --no-verify --amend -m "${OUTPUT}" > commit.log
#
## install to check setup
#pip uninstall -y spectrochempy
#pip install -e . || exit 1




