#!/bin/bash


#source ~/.bash_profile

# to make it work with matplotlib/latex
#export PATH=$PATH:/Library/TeX/texbin/

# test everything and do not commit if errors
py.test  -x "not example" --nodisplay --reset_config tests || exit 1

## install to check setup
pip uninstall -y spectrochempy
pip install -e . || exit 1

python docs/builddocs.py html 


