#!/bin/bash

# run test for python 3.6
#-------------------------

# to make it work with SourceTree (assuming anaconda is used)
# probably need to change this to account for windows developper..
# TODO: activate in windows?

source ~/.bash_profile

# test everything and do not commit if errors
py.test -x tests || exit 1

# install to check setup
pip uninstall -y spectrochempy
pip install -e . || exit 1

# add files modified
git add spectrochempy/version.py







