{% set name = "SpectroChemPy" %}
{% set version = environ['VERSION'] %}
{% set devstring = environ['DEVSTRING'] %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ../

build:
  script_env:
    - VERSION
    - DEVSTRING
    - CONDA_BLD_PATH
  string: "{{ devstring }}"
  noarch: python
  script:  "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - scpy=spectrochempy.scripts.launch_api:main

requirements:
  host:
    - python
  build:
    - python
    - setuptools
    - setuptools_scm
    - nodejs
    - jupyterlab
  run:
    - numpy
    - scipy
    - pandas
    - matplotlib
    - traitlets
    - pint
    - quaternion
    - pyqt
    - colorama
    - tqdm
    - ipython
    - numba
    - cantera
    - quadprog
    - brukeropusreader
    - requests
    - jinja2
    - nmrglue
    - docrep
    - orderedset
    - xlrd
    - setuptools_scm
    - git
    - ipywidgets
    - ipympl
    - jupyterlab
    - nodejs
  test:
    - python                {{ python }}

test:
  script_env:
    - VERSION
    - DEVSTRING
    - CONDA_BLD_PATH
  imports:
    - spectrochempy

about:
  home: "https://github.com/spectrochempy/spectrochempy"
  license: CeCILL-B
  license_family: OTHER
  summary: "Processing, analysis and modelling Spectroscopic data for Chemistry with Python"
  doc_url: "https://www.spectrochempy.fr"
  dev_url: "https://github.com/spectrochempy/spectrochempy"

extra:
  recipe-maintainers:
    - fernandezc
