__all__ = []

nmr_valid_meta = [
    #		('amp', ''),
    ('aq_mod', ''),
    ('aqseq', ''),
    #		('aunm', ''),
    #		('autopos', ''),
    ('bf1', 'MHz'),
    ('bf2', 'MHz'),
    ('bf3', 'MHz'),
    ('bf4', 'MHz'),
    #  		('bf5', 'MHz'),
    #  		('bf6', 'MHz'),
    #  		('bf7', 'MHz'),
    #  		('bf8', 'MHz'),
    #		('bytorda', ''),
    #		('cfdgtyp', ''),
    #		('cfrgtyp', ''),
    #		('chemstr', ''),
    ('cnst', ''),
    #		('cpdprg', ''),
    #		('cpdprg1', ''),
    #		('cpdprg2', ''),
    #		('cpdprg3', ''),
    #		('cpdprg4', ''),
    #		('cpdprg5', ''),
    #		('cpdprg6', ''),
    #		('cpdprg7', ''),
    #		('cpdprg8', ''),
    #		('cpdprgb', ''),
    #		('cpdprgt', ''),
    ('d', 's'),
    ('date', ''),
    #		('dbl', ''),
    #		('dbp', ''),
    #		('dbp07', ''),
    #		('dbpnam0', ''),
    #		('dbpnam1', ''),
    #		('dbpnam2', ''),
    #		('dbpnam3', ''),
    #		('dbpnam4', ''),
    #		('dbpnam5', ''),
    #		('dbpnam6', ''),
    #		('dbpnam7', ''),
    #		('dbpoal', ''),
    #		('dbpoffs', ''),
    ('de', 'us'),
    #		('decbnuc', ''),
    #		('decim', ''),
    #		('decnuc', ''),
    #		('decstat', ''),
    ('digmod', ''),
    #		('digtyp', ''),
    #		('dl', ''),
    #		('dp', ''),
    #		('dp07', ''),
    #		('dpname0', ''),
    #		('dpname1', ''),
    #		('dpname2', ''),
    #		('dpname3', ''),
    #		('dpname4', ''),
    #		('dpname5', ''),
    #		('dpname6', ''),
    #		('dpname7', ''),
    #		('dpoal', ''),
    #		('dpoffs', ''),
    #		('dqdmode', ''),
    #		('dr', ''),
    #		('ds', ''),
    #		('dslist', ''),
    #		('dspfirm', ''),
    #		('dspfvs', ''),
    #		('dtypa', ''),
    #		('exp', ''),
    #		('f1list', ''),
    #		('f2list', ''),
    #		('f3list', ''),
    #		('fcuchan', ''),
    #		('file_size', ''),
    #		('fl1', ''),
    #		('fl2', ''),
    #		('fl3', ''),
    #		('fl4', ''),
    ('fnmode', ''),
    #		('fov', ''),
    #		('fq1list', ''),
    #		('fq2list', ''),
    #		('fq3list', ''),
    #		('fq4list', ''),
    #		('fq5list', ''),
    #		('fq6list', ''),
    #		('fq7list', ''),
    #		('fq8list', ''),
    #		('fs', ''),
    #		('ftlpgn', ''),
    #		('fw', ''),
    #		('gp031', ''),
    #		('gpnam0', ''),
    #		('gpnam1', ''),
    #		('gpnam10', ''),
    #		('gpnam11', ''),
    #		('gpnam12', ''),
    #		('gpnam13', ''),
    #		('gpnam14', ''),
    #		('gpnam15', ''),
    #		('gpnam16', ''),
    #		('gpnam17', ''),
    #		('gpnam18', ''),
    #		('gpnam19', ''),
    #		('gpnam2', ''),
    #		('gpnam20', ''),
    #		('gpnam21', ''),
    #		('gpnam22', ''),
    #		('gpnam23', ''),
    #		('gpnam24', ''),
    #		('gpnam25', ''),
    #		('gpnam26', ''),
    #		('gpnam27', ''),
    #		('gpnam28', ''),
    #		('gpnam29', ''),
    #		('gpnam3', ''),
    #		('gpnam30', ''),
    #		('gpnam31', ''),
    #		('gpnam4', ''),
    #		('gpnam5', ''),
    #		('gpnam6', ''),
    #		('gpnam7', ''),
    #		('gpnam8', ''),
    #		('gpnam9', ''),
    #		('gpx', ''),
    #		('gpy', ''),
    #		('gpz', ''),
    #		('grdprog', ''),
    #		('hdduty', ''),
    #		('hdrate', ''),
    #		('hgain', ''),
    #		('hl1', ''),
    #		('hl2', ''),
    #		('hl3', ''),
    #		('hl4', ''),
    #		('holder', ''),
    #		('hpmod', ''),
    #		('hpprgn', ''),
    #		('in', ''),
    #		('inp', ''),
    #		('instrum', ''),
    #		('l', ''),
    #		('lfilter', ''),
    #		('lgain', ''),
    #		('locked', ''),
    #		('lockfld', ''),
    #		('lockgn', ''),
    #		('lockpow', ''),
    #		('lockppm', ''),
    #		('locnuc', ''),
    #		('locphas', ''),
    #		('locshft', ''),
    #		('ltime', ''),
    ('masr', 'Hz'),
    #		('masrlst', ''),
    #		('nbl', ''),
    ('nc', ''),
    ('ns', ''),
    ('nuc1', ''),
    ('nuc2', ''),
    ('nuc3', ''),
    ('nuc4', ''),
    #  		('nuc5', ''),
    #  		('nuc6', ''),
    #		('nuc7', ''),
    #		('nuc8', ''),
    ('nuclei', ''),
    ('nucleus', ''),
    ('o1', 'Hz'),
    ('o2', 'Hz'),
    ('o3', 'Hz'),
    ('o4', 'Hz'),
    #  		('o5', 'Hz'),
    #  		('o6', 'Hz'),
    #  		('o7', 'Hz'),
    #  		('o8', 'Hz'),
    #		('obschan', ''),
    #		('overflw', ''),
    ('p', 'us'),
    #		('paps', ''),
    ('parmode', ''),
    #		('pcpd', ''),
    ('ph_ref', ''),
    ('phcor', ''),
    #		('php', ''),
    ('pl', ''),
    #		('powmod', ''),
    #		('pr', ''),
    #		('prechan', ''),
    #		('prgain', ''),
    #		('probhd', ''),
    #		('prosol', ''),
    ('pulprog', ''),
    ('pw', 'W'),
    #		('qnp', ''),
    #		('qs', ''),
    #		('qsb', ''),
    #		('rd', ''),
    #		('recchan', ''),
    #		('recph', ''),
    ('rg', ''),
    #		('ro', ''),
    #		('routwd1', ''),
    #		('routwd2', ''),
    #		('rpuused', ''),
    #		('rsel', ''),
    #		('s', ''),
    #		('seout', ''),
    ('sfo1', 'MHz'),
    ('sfo2', 'MHz'),
    ('sfo3', 'MHz'),
    ('sfo4', 'MHz'),
    #		('sfo5', 'MHz'),
    #		('sfo6', 'MHz'),
    #		('sfo7', 'MHz'),
    #		('sfo8', 'MHz'),
    #		('solvent', ''),
    #		('sp', ''),
    #		('sp07', ''),
    #		('spectr', ''),
    #		('spnam0', ''),
    #		('spnam1', ''),
    #		('spnam10', ''),
    #		('spnam11', ''),
    #		('spnam12', ''),
    #		('spnam13', ''),
    #		('spnam14', ''),
    #		('spnam15', ''),
    #		('spnam16', ''),
    #		('spnam17', ''),
    #		('spnam18', ''),
    #		('spnam19', ''),
    #		('spnam2', ''),
    #		('spnam20', ''),
    #		('spnam21', ''),
    #		('spnam22', ''),
    #		('spnam23', ''),
    #		('spnam24', ''),
    #		('spnam25', ''),
    #		('spnam26', ''),
    #		('spnam27', ''),
    #		('spnam28', ''),
    #		('spnam29', ''),
    #		('spnam3', ''),
    #		('spnam30', ''),
    #		('spnam31', ''),
    #		('spnam4', ''),
    #		('spnam5', ''),
    #		('spnam6', ''),
    #		('spnam7', ''),
    #		('spnam8', ''),
    #		('spnam9', ''),
    #		('spoal', ''),
    #		('spoffs', ''),
    #		('subnam0', ''),
    #		('subnam1', ''),
    #		('subnam2', ''),
    #		('subnam3', ''),
    #		('subnam4', ''),
    #		('subnam5', ''),
    #		('subnam6', ''),
    #		('subnam7', ''),
    #		('subnam8', ''),
    #		('subnam9', ''),
    ('sw', 'ppm'),
    ('sw_h', 'Hz'),
    #		('swibox', ''),
    ('td', ''),
    #		('td0', ''),
    ('te', 'K'),
    #		('te2', ''),
    #		('te3', ''),
    #		('teg', ''),
    #		('tl', ''),
    #		('tp', ''),
    #		('tp07', ''),
    #		('tpname0', ''),
    #		('tpname1', ''),
    #		('tpname2', ''),
    #		('tpname3', ''),
    #		('tpname4', ''),
    #		('tpname5', ''),
    #		('tpname6', ''),
    #		('tpname7', ''),
    #		('tpoal', ''),
    #		('tpoffs', ''),
    #		('tunhin', ''),
    #		('tunhout', ''),
    #		('tunxout', ''),
    #		('usera1', ''),
    #		('usera2', ''),
    #		('usera3', ''),
    #		('usera4', ''),
    #		('usera5', ''),
    #		('v9', ''),
    ('valist', ''),
    ('vclist', ''),
    ('vd', ''),
    ('vdlist', ''),
    ('vplist', ''),
    ('vtlist', ''),
    #		('wbst', ''),
    #		('wbsw', ''),
    #		('ws', ''),
    #		('xgain', ''),
    #		('xl', ''),
    #		('yl', ''),
    #		('ymax_a', ''),
    #		('ymin_a', ''),
    #		('zgoptns', ''),
    #		('zl1', ''),
    #		('zl2', ''),
    #		('zl3', ''),
    #		('zl4', ''),
    # PROCS
    # ('absf1', ''),
    # ('absf2', ''),
    # ('absg', ''),
    # ('absl', ''),
    # ('acqt0', ''),
    # ('alpha', ''),
    # ('ampcoil', ''),
    # ('anavpt', ''),
    ('aqorder', ''),
    # ('assfac', ''),
    # ('assfaci', ''),
    # ('assfacx', ''),
    # ('asswid', ''),
    # ('aunmp', ''),
    # ('axleft', ''),
    # ('axname', ''),
    # ('axnuc', ''),
    # ('axright', ''),
    # ('axtype', ''),
    # ('axunit', ''),
    # ('azfe', ''),
    # ('azfw', ''),
    # ('bc_mod', ''),
    # ('bcfw', ''),
    # ('bytordp', ''),
    # ('cagpars', ''),
    # ('coroffs', ''),
    # ('cy', ''),
    # ('datmod', ''),
    # ('dc', ''),
    # ('dfilt', ''),
    # ('dtypp', ''),
    # ('eretic', ''),
    # ('f1p', ''),
    # ('f2p', ''),
    # ('fcor', ''),
    # ('fntype', ''),
    # ('frqlo3', ''),
    # ('frqlo3n', ''),
    # ('ft_mod', ''),
    # ('ftsize', ''),
    # ('gamma', ''),
    # ('gb', 'Hz' ),
    # ('gpnam', ''),
    # ('grpdly', ''),
    # ('inf', ''),
    # ('intbc', ''),
    # ('intscl', ''),
    # ('isen', ''),
    # ('lb', 'Hz' ),
    # ('lev0', ''),
    # ('linpstp', ''),
    # ('locsw', ''),
    # ('lpbin', ''),
    # ('maxi', ''),
    ('mc2', ''),
    # ('mdd_csalg', ''),
    # ('mdd_cslambda', ''),
    # ('mdd_csniter', ''),
    # ('mdd_csnorm', ''),
    # ('mdd_cszf', ''),
    # ('mdd_mod', ''),
    # ('mddcexp', ''),
    # ('mddct_sp', ''),
    # ('mddf180', ''),
    # ('mddlambda', ''),
    # ('mddmemory', ''),
    # ('mddmerge', ''),
    # ('mddncomp', ''),
    # ('mddniter', ''),
    # ('mddnoise', ''),
    # ('mddphase', ''),
    # ('mddseed', ''),
    # ('mddsrsize', ''),
    # ('me_mod', ''),
    # ('mean', ''),
    # ('mi', ''),
    # ('mulexpno', ''),
    # ('nc_proc', ''),
    # ('ncoef', ''),
    # ('nlev', ''),
    # ('nlogch', ''),
    # ('noisf1', ''),
    # ('noisf2', ''),
    # ('novflw', ''),
    # ('nsp', ''),
    # ('nth_pi', ''),
    # ('nusamount', ''),
    # ('nusfpnz', ''),
    # ('nusjsp', ''),
    # ('nuslist', ''),
    # ('nusseed', ''),
    # ('nust2', ''),
    # ('nustd', ''),
    # ('nzp', ''),
    # ('offset', ''),
    # ('pacoil', ''),
    # ('pc', ''),
    # ('pexsel', ''),
    # ('ph_mod', ''),
    ('phc0',  'deg'),
    ('phc1',  'deg'),
    # ('phlist', ''),
    # ('pknl', ''),
    # ('plstep', ''),
    # ('plstrt', ''),
    # ('plw', ''),
    # ('plwmax', ''),
    # ('pparmod', ''),
    # ('ppdiag', ''),
    # ('ppiptyp', ''),
    # ('ppmpnum', ''),
    # ('ppresol', ''),
    # ('pqphase', ''),
    # ('pqscale', ''),
    # ('pscal', ''),
    # ('psign', ''),
    # ('pynm', ''),
    # ('pynmp', ''),
    # ('recpre', ''),
    # ('recprfx', ''),
    # ('recsel', ''),
    ('reverse', ''),
    # ('s_dev', ''),
    # ('selrec', ''),
    ('sf', 'MHz'),
    # ('si', ''),
    # ('sigf1', ''),
    # ('sigf2', ''),
    # ('sino', ''),
    # ('siold', ''),
    # ('solvold', ''),
    # ('spectyp', ''),
    # ('spincnt', ''),
    # ('spnam', ''),
    # ('sppex', ''),
    # ('spw', ''),
    # ('sreglst', ''),
    # ('ssb', ''),
    # ('stsi', ''),
    # ('stsr', ''),
    # ('subnam', ''),
    # ('sw_p', ''),
    # ('swfinal', ''),
    # ('symm', ''),
    # ('tdeff', ''),
    # ('tdoff', ''),
    # ('te1', ''),
    # ('te4', ''),
    # ('te_pidx', ''),
    # ('te_stab', ''),
    # ('ti', ''),
    # ('tilt', ''),
    # ('tm1', ''),
    # ('tm2', ''),
    # ('toplev', ''),
    # ('userp1', ''),
    # ('userp2', ''),
    # ('userp3', ''),
    # ('userp4', ''),
    # ('userp5', ''),
    # ('wdw', ''),
    # ('xdim', ''),
    # ('ymax_p', ''),
    # ('ymin_p', ''),
]
