{% set name = "SpectroChemPy" %}

{% set version = environ['VERSION'] %}

{% set devstring = environ['DEVSTRING'] %}


package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ../

build:
  script_env:
    - VERSION
    - DEVSTRING
    - CONDA_BLD_PATH
  string: "{{ devstring }}"
  noarch: python
  script:
    - export SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
    - {{ PYTHON }} -m pip install .

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools
    - setuptools_scm
    - nodejs
    - jupyterlab >=2.2.10
    - matplotlib-base

  run:
    - quadprog
    - brukeropusreader
    - quaternion
    - colorama
    - dill
    - ipython>=7.31.1
    - jinja2<3.1
    - mamba
    - matplotlib>=3.5
    - numba=0.55.0
    - numpy=1.21.5
    - pint>=0.18
    - requests
    - scipy=1.7.3
    - tqdm
    - traitlets<5.2
    - traittypes
    - xlrd
    - setuptools
    - setuptools_scm
    - git
    - pyyaml
    - ipywidgets
    - ipympl
    - jupyterlab >=2.2.10
    - nodejs

  test:
    - python                {{ python }}

test:
  script_env:
    - VERSION
    - DEVSTRING
    - CONDA_BLD_PATH
  imports:
    - spectrochempy

about:
  home: "https://github.com/spectrochempy/spectrochempy"
  license: CeCILL-B
  license_family: OTHER
  summary: "Processing, analysis and modelling Spectroscopic data for Chemistry with Python"
  doc_url: "https://www.spectrochempy.fr"
  dev_url: "https://github.com/spectrochempy/spectrochempy"
  description: |
    SpectroChemPy is a framework for processing, analyzing and modeling Spectroscopic data for Chemistry with Python.
    It is a cross platform software, running on Linux, Windows or OS X.

    SpectroChemPy is still experimental and under active development.
    Its current design is subject to major changes, reorganizations, bugs and crashes!!!.
    Please report any issues to the Issue Tracker on github.

extra:
  recipe-maintainers:
    - fernandezc
