name: Install on Colab

on:
  push:
    branches:
      - master
      - develop
      - feature/*
      - fix/*
      - docs/*

jobs:
  test:
    name: Test run on latest colab image
    runs-on: ubuntu-latest

    steps:
     - name: Init space
       run: |
         echo "Free space available: $(df -h / | awk '{print $4}' | tail -n 1)"
       
     - name: Maximize build space
       uses: AdityaGarg8/remove-unwanted-software@v4.1
       with:
         remove-android: 'true'
         remove-haskell: 'true'
         remove-codeql: 'true'
         
     - name: Install Colab Docker image
       run: |
         echo "Free space available: $(df -h / | awk '{print $4}' | tail -n 1)"
         echo "Installing Colab Docker image..."
         docker pull europe-docker.pkg.dev/colab-images/public/runtime:latest
         echo "Colab Docker image installed."
         echo "Free space available: $(df -h / | awk '{print $4}' | tail -n 1)"
        
     - uses: actions/checkout@v4
     - name: Install scp dependencies
       run: |
        echo "Installing spectrochempy dependencies ..."
        python -m pip install -r ./requirements/requirements.txt 
        python -m pip install .
