name: Install on Colab

on:
  push:
    branches:
      - master
      - develop
      - feature/*
      - fix/*
      - docs/*

jobs:
  test:
    name: Test run on latest colab image
    runs-on: ubuntu-latest-4core

    container:
      image: europe-docker.pkg.dev/colab-images/public/runtime:latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        # Install any necessary Python packages here
        python -m pip install -r https://raw.githubusercontent.com/${{github.repository}}/requirements/requirements.txt 
        git clone --depth=1 https://github.com/${{github.repository}}/spectrochempy.git
        python -m pip install ./spectrochempy
