name: Python Package using Conda

on: 
  push:
    branches:
      - develop

jobs:
  build-linux:
    name: Build Linux
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Add conda to system path
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH
      - name: Install dependencies
        run: |
          conda install jinja2
          python .ci/env/env_create.py -v 3.8 --dev scpy3.8.yml
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: scpy3.8
          environment-file: .ci/env/scpy3.8.yml
          python-version: 3.8
          condarc-file: .ci/env/condarc.yml
          auto-activate-base: false
      - name: install spectrochempy
        run: |
          python setup.py install
      - name: display info
        run: |
          conda info
          conda list
      - name: Lint with flake8
        run: |
          mamba install flake8
          flake8 .
      - name: Test with pytest
        run: |
          mamba install pytest
          pytest

